"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { MeshTransmissionMaterial, useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { useScroll, useTransform } from "motion/react";

export function Model({
  enableFloatingEffect,
  enableRotatingEffect,
  enableScrollEffect,
  position,
  rotation,
  scale,
  props,
}) {
  // VARIABLES EFFET LEVITATION / FLOAT EFFECT VARS
  // const enableFloatingEffect = true;
  const floatSpeed = 0.9;
  const floatAmplitude = 0.09;

  // VARIABLES EFFET ROTATION / ONSCROLL ROTATION EFFECT VARS
  // const enableRotatingEffect = true;
  const rotationSpeed = 1.3;
  const baseXRotation = -0.6;

  const { nodes, materials } = useGLTF("/3d/logoOpti.glb");
  const { size } = useThree();

  const targetRef = useRef(); // prettier-ignore

  const { height: h } = useThree((state) => state.viewport);

  const { scrollYProgress } = useScroll();

  // REMPLACER XX , XX PAR LE POURCENTAGE DE DEBUT ET DE FIN
  // DE LA PROGRESSION DU SCROLLPROGRESS (ENTRE 0 ET 1)
  //(scrollYProgress, [XX, XX], [h / 4, h / -4]);
  const positionY = useTransform(
    scrollYProgress,
    [0.057, 0.14],
    [h / 4, h / -4]
  );
  const rotationX = useTransform(scrollYProgress, [0.057, 0.14], [0, 1.9]);

  //A CHAQUE FRAME, changer la position et la roation si scroll, floatingEffect() et rotatingEffect()
  useFrame(() => {
    if (enableScrollEffect) {
      if (!targetRef.current) return;
      targetRef.current.position.y = positionY.get() * 1.2;
      targetRef.current.rotation.x =
        rotationX.get() * rotationSpeed + baseXRotation;
      // console.log(targetRef.current.position);
      console.log(scrollYProgress.get());
    }
  });
  if (enableFloatingEffect) {
    useFrame(() => {
      floatingEffect();
    });
  }
  if (enableRotatingEffect) {
    useFrame(() => {
      rotatingEffect();
    });
  }

  //EFFET LEVITATION
  function floatingEffect() {
    const floatOffset =
      Math.sin(Date.now() * 0.001 * floatSpeed) * floatAmplitude;
    targetRef.current.position.y += floatOffset;
  }

  //EFFET AUTO-ROTATION
  function rotatingEffect() {
    targetRef.current.rotation.z += 0.003;
  }

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={targetRef}
        position={position}
        castShadow
        receiveShadow
        geometry={nodes.Curve001.geometry}
        material={materials["SVGMat.004"]}
        rotation={rotation}
        scale={scale ?? (size.width >= 1024 ? 12 : 10)}
      >
        {/* <MeshTransmissionMaterial
          thickness={0}
          roughness={0}
          transmission={1}
          ior={1}
          chromaticAberration={0.02}
          backside={true}
        /> */}
      </mesh>
    </group>
  );
}

useGLTF.preload("/3d/logoOpti.glb");
