/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Piece({
  enableRotatingEffect,
  position,
  rotation,
  scale,
  onClick,
  props,
}) {
  const { nodes, materials } = useGLTF("/3d/PIECE SITE.glb");
  const pieceRef = useRef(); // prettier-ignore
  const [hovered, setHover] = useState(false);

  if (enableRotatingEffect) {
    useFrame(() => {
      rotatingEffect();
    });
  }

  function rotatingEffect() {
    pieceRef.current.rotation.z += 0.053;
  }
  return (
    <group {...props} dispose={null}>
      <mesh
        ref={pieceRef}
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.001"]}
        position={position}
        scale={hovered ? scale + 1 : scale}
        rotation={rotation}
        onClick={onClick}
        // onPointerOver={(event) => setHover(true)}
        // onPointerOut={(event) => setHover(false)}
      />
    </group>
  );
}

useGLTF.preload("/3d/PIECE SITE.glb");
