"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { MeshTransmissionMaterial, useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { useScroll, useTransform } from "motion/react";

export function Model(props) {
  // VARIABLES EFFET LEVITATION / FLOAT EFFECT VARS
  const enableFloatingEffect = true;
  const floatSpeed = 1.1;
  const floatAmplitude = 0.09;

  // VARIABLES EFFET ROTATION / ONSCROLL ROTATION EFFECT VARS
  const enableRotatingEffect = true;
  const rotationSpeed = 6;
  const baseXRotation = -0.6;

  const { nodes, materials } = useGLTF("/logoOpti.glb");
  const { size } = useThree();

  const targetRef = useRef(); // prettier-ignore

  const { height: h } = useThree((state) => state.viewport);

  const { scrollYProgress } = useScroll();

  // REMPLACER XX , XX PAR LE POURCENTAGE DE DEBUT ET DE FIN
  // DE LA PROGRESSION DU SCROLLPROGRESS (ENTRE 0 ET 1)
  //(scrollYProgress, [XX, XX], [h / 4, h / -4]);
  const positionY = useTransform(scrollYProgress, [0.23, 0.6], [h / 4, h / -4]);
  const rotationX = useTransform(scrollYProgress, [0.23, 0.6], [0, 1.9]);

  //A CHAQUE FRAME, changer la position et la roation si scroll, floatingEffect() et rotatingEffect()
  useFrame(() => {
    if (!targetRef.current) return;
    targetRef.current.position.y = positionY.get() * 1.2;
    targetRef.current.rotation.x =
      rotationX.get() * rotationSpeed + baseXRotation;
    // console.log(targetRef.current.position);
    console.log(scrollYProgress.get());

    floatingEffect();
    rotatingEffect();
  });

  //EFFET LEVITATION
  function floatingEffect() {
    if (enableFloatingEffect) {
      const floatOffset =
        Math.sin(Date.now() * 0.001 * floatSpeed) * floatAmplitude;
      targetRef.current.position.y += floatOffset;
    }
  }

  //EFFET AUTO-ROTATION
  function rotatingEffect() {
    if (enableRotatingEffect) {
      targetRef.current.rotation.z += 0.003;
    }
  }

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={targetRef}
        position={[0, 2, 0]}
        castShadow
        receiveShadow
        geometry={nodes.Curve001.geometry}
        material={materials["SVGMat.004"]}
        rotation={[0, -0.65, 0.5]}
        scale={size.width >= 1024 ? 12 : 10}
      ></mesh>
    </group>
  );
}

useGLTF.preload("/logoOpti.glb");
