/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Piece({
  enableRotatingEffect,
  position,
  rotation,
  scale,
  onClick,
  props,
}) {
  const { nodes, materials } = useGLTF("/PIECE SITE.glb");
  const pieceRef = useRef(); // prettier-ignore
  const [hovered, setHover] = useState(false);

  //EFFET AUTO-ROTATION
  function rotatingEffect() {
    if (enableRotatingEffect) {
      hovered
        ? (pieceRef.current.rotation.z += 0.008)
        : (pieceRef.current.rotation.z += 0.001);
    }
  }

  useFrame(() => {
    rotatingEffect();
  });
  return (
    <group {...props} dispose={null}>
      <mesh
        ref={pieceRef}
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.001"]}
        position={position}
        scale={hovered ? scale + 1 : scale}
        rotation={rotation}
        onClick={onClick}
        // onPointerOver={(event) => setHover(true)}
        // onPointerOut={(event) => setHover(false)}
      />
    </group>
  );
}

useGLTF.preload("/PIECE SITE.glb");
